Repository ShikhaMaurya212402/Plant-Disease-Classification-Model, pull requests merged in 2025-06, with the labels that each got.

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#30 Basic Front End code
  frontend/plant/.gitignore
  frontend/plant/README.md
  frontend/plant/package-lock.json
  frontend/plant/package.json
  frontend/plant/public/favicon.ico
  frontend/plant/public/index.html
  frontend/plant/public/logo192.png
  frontend/plant/public/logo512.png
  frontend/plant/public/manifest.json
  frontend/plant/public/robots.txt
  frontend/plant/public/theme.css
  frontend/plant/src/App.css
  frontend/plant/src/App.js
  frontend/plant/src/App.test.js
  frontend/plant/src/components/Classification/ClassificationResult.css
  frontend/plant/src/components/Classification/ClassificationResult.jsx
  frontend/plant/src/components/Classification/DiseaseCard.css
  frontend/plant/src/components/Classification/DiseaseCard.jsx
  frontend/plant/src/components/Classification/TreatmentInfo.css
  frontend/plant/src/components/Classification/TreatmentInfo.jsx
  frontend/plant/src/components/History/HistoryItem.css
  frontend/plant/src/components/History/HistoryItem.jsx
  frontend/plant/src/components/History/HistoryList.css
  frontend/plant/src/components/History/HistoryList.jsx
  frontend/plant/src/components/ImageUpload/DropZone.css
  frontend/plant/src/components/ImageUpload/DropZone.jsx
  frontend/plant/src/components/ImageUpload/ImagePreview.css
  frontend/plant/src/components/ImageUpload/ImagePreview.jsx
  frontend/plant/src/components/ImageUpload/ImageUpload.css
  frontend/plant/src/components/ImageUpload/ImageUpload.jsx
  frontend/plant/src/components/common/ErrorBoundary.css
  frontend/plant/src/components/common/ErrorBoundary.jsx
  frontend/plant/src/components/common/Footer.css
  frontend/plant/src/components/common/Footer.jsx
  frontend/plant/src/components/common/Header.css
  frontend/plant/src/components/common/Header.jsx
  frontend/plant/src/components/common/Loader.css
  frontend/plant/src/components/common/Loader.jsx
  frontend/plant/src/index.css
  frontend/plant/src/index.js
  frontend/plant/src/logo.svg
  frontend/plant/src/pages/About.css
  frontend/plant/src/pages/About.jsx
  frontend/plant/src/pages/Classify.css
  frontend/plant/src/pages/Classify.jsx
  frontend/plant/src/pages/History.css
  frontend/plant/src/pages/History.jsx
  frontend/plant/src/pages/Home.css
  frontend/plant/src/pages/Home.jsx
  frontend/plant/src/pages/NotFound.css
  frontend/plant/src/pages/NotFound.jsx
  frontend/plant/src/reportWebVitals.js
  frontend/plant/src/setupTests.js
  frontend/plant/src/styles/globals.css
Labels: enhancement

#35 Enhanced README with details about project, setup instruction and formatting.
  README.md
Labels: documentation, Beginner
