Repository ShikhaMaurya212402/Plant-Disease-Classification-Model, pull requests merged in 2025-07, with the labels that each got.

#26 Add requirements.txt for project dependencies
  requirements.txt
Labels: documentation, Beginner

#43 Added scroll to top button
  frontend/plant/src/App.js
  frontend/plant/src/components/common/ScrollToTop.css
  frontend/plant/src/components/common/ScrollToTop.jsx
Labels: enhancement, Beginner

#44 Added Markdown-based GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom_issue.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/performance.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation, Beginner

#46 UI update
  frontend/plant/public/faavv.svg
  frontend/plant/public/favicon.ico
  frontend/plant/public/index.html
  frontend/plant/public/logo192.png
  frontend/plant/public/logo512.png
  frontend/plant/public/manifest.json
  frontend/plant/src/LOGG.svg
  frontend/plant/src/components/common/Footer.jsx
  frontend/plant/src/components/common/Header.jsx
  frontend/plant/src/components/common/LOGGO.svg
  frontend/plant/src/components/common/loggw.svg
  frontend/plant/src/loggw.svg
Labels: Creative, Beginner

#52 Pretrained Model for improving accuracy
  PlantDiseasePretrainedModel.ipynb
Labels: enhancement, Advanced
